#! /bin/sh

xss-lock -- i3lock -i /home/michael/Wallpapers/dancehall-3000x2000.png -f -e -I 5 &
/home/michael/dotfiles/scripts/wallpaper.py &
#set mouse
synclient TapButton1=1
synclient TapButton2=2
synclient TapButton3=3

export GDK_SCALE=2
export GDK_DPI_SCALE=0.6

xinput set-prop "SYNA1D31:00 06CB:CD48 Touchpad" "libinput Tapping Enabled" 1

pcloud &
gnome-keyring-daemon
